### ISSUE TITLE
Air Date not being fetched

### ISSUE THREAD

**Issue by programVeins** [benjaminbruch/Rick-and-Morty-Swift-API#2]
Air date of an episode, for some reason, isn't fetched/working properly. It displays the default value of 'air_date' (the string itself)

**Comment by benjaminbruch** [comment]
Hey Sabesh,

Sry for the late answer, I wasn't notified that you have created an issue. I will have a look in the next days. What version did you use?

**Comment by benjaminbruch** [comment]
Should be ok with latest release: https://github.com/benjaminbruch/Rick-and-Morty-Swift-API/releases/tag/v2.0
